name = "smart-study-planner"

main = ".open-next/worker.js"
compatibility_date = "2024-09-23" # Use a recent date
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }
[vars]
# Add environment variables here

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]

[[d1_databases]]
binding = "DB"
database_name = "smart-study-planner-db"
database_id = "55b6575b-e05e-449a-ba72-2acc2d3cb1dd"
